"""create initial tables

Revision ID: ed552ac9ae64
Revises: 
Create Date: 2026-07-19 19:40:04.300093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed552ac9ae64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('block_hash', sa.String(length=66), nullable=False),
    sa.Column('parent_hash', sa.String(length=66), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_block_hash'), 'blocks', ['block_hash'], unique=True)
    op.create_index(op.f('ix_blocks_number'), 'blocks', ['number'], unique=True)
    op.create_table('indexer_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chain_id', sa.BigInteger(), nullable=False),
    sa.Column('latest_indexed_block', sa.BigInteger(), nullable=False),
    sa.Column('latest_confirmed_block', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexer_states_chain_id'), 'indexer_states', ['chain_id'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('transaction_index', sa.Integer(), nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=True),
    sa.Column('value', sa.Numeric(precision=78, scale=0), nullable=False),
    sa.Column('gas', sa.BigInteger(), nullable=False),
    sa.Column('gas_price', sa.Numeric(precision=78, scale=0), nullable=True),
    sa.Column('nonce', sa.BigInteger(), nullable=False),
    sa.Column('input_data', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_number'], ['blocks.number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_block_number'), 'transactions', ['block_number'], unique=False)
    op.create_index(op.f('ix_transactions_from_address'), 'transactions', ['from_address'], unique=False)
    op.create_index(op.f('ix_transactions_to_address'), 'transactions', ['to_address'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_hash'), 'transactions', ['transaction_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_to_address'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_address'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_block_number'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_indexer_states_chain_id'), table_name='indexer_states')
    op.drop_table('indexer_states')
    op.drop_index(op.f('ix_blocks_number'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_hash'), table_name='blocks')
    op.drop_table('blocks')
    # ### end Alembic commands ###
